#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ../../generate_options
../../generate_clear

ln -s ../../img_photos/rings_* .

. ../../generate_examples

# for Nicholas' section
./generate_sigmoidized
./generate_linear
./generate_srgb
./generate_downsize
./generate_lab

../../generate_compare
echo "DONE"

