#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ../generate_options
../generate_clear

ln -s ../images/storm.gif .
ln -s ../img_photos/rings_* .

. ../generate_examples

# Extra Images...
./generate_graphs
./generate_enlarge
./generate_shrink
./generate_smaller

../generate_compare
echo "DONE"

