#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ../generate_options
../generate_clear

#ln -s ../images/dragon_sm.gif dragon.gif
#ln -s ../images/terminal.gif .
ln -s ../images/storm.gif .
#ln -s ../images/rose.gif .
#ln -s ../images/rose.png .
ln -s ../img_photos/rings_* .
#ln -s ../img_photos/earth_lights_4800.tif .

. ../generate_examples

# Extra Images...
./generate_graphs
./generate_enlarge
./generate_shrink
./generate_smaller

../generate_compare
echo "DONE"

