#!/bin/sh
#
# Generate a motage array using various resize filters
# to shrink a crop of the rings image
#
echo "Generating Resize Filters Montage (shrink)..."

. ../generate_options

for filter in Box Hermite Triangle \
              Gaussian Quadratic Spline \
              Lanczos Hamming Blackman \
              Lagrange Catrom Mitchell \
;do
  if [ "$filter" = 'null:' ]; then
    convert null: miff:-
  else
    convert -label $filter rings_crop.png \
            -filter $filter -resize 100x  miff:-
  fi
done |
  montage -  -tile 6x  -geometry +4+2  -pointsize 10 \
          -background $page_bg_color -mattecolor $page_bg_color \
          montage_shrink.png

chmod 644 montage_shrink.png


