#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ../generate_options
../generate_clear

ln -s ../anim_basics/canvas_{prev,bgnd}.gif .
ln -s ../anim_basics/anim_bgnd.gif .
ln -s ../images/{balloon,medical,present,shading}.gif .
ln -s ../images/script_[ok].gif .
ln -s ../images/bag_{left,right}.gif .
ln -s ../images/neon_[helo].gif .
ln -s ../images/glitter_*.gif .
ln -s ../images/logo.gif .

../generate_examples

../generate_compare
echo "DONE"

