#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ../generate_options
../generate_clear
#jpg_opt='-quality 100%'

ln -s ../images/tile_fabric.gif .
ln -s ../images/piglet.gif .
ln -s ../images/ny_family* .
ln -s ../img_photos/pagoda_sm.jpg .
ln -s ../img_photos/night_club_* .
ln -s ../img_photos/night_scape_* .
ln -s ../img_photos/holocaust_sm.jpg .
ln -s ../img_photos/holocaust_tn.gif .
ln -s ../img_photos/hatching_tn.gif .
ln -s ../img_photos/beijing_md.jpg .
ln -s ../img_photos/spiral_stairs_tn.gif .
ln -s ../img_photos/chinese_chess_tn.gif .
ln -s ../img_photos/anthony_*.jpg .
ln -s ../img_photos/jacob_vs_jacob_md.jpg .
ln -s ../img_photos/vegas_* .
ln -s ../img_photos/nikon* .
ln -s ../img_photos/zelda_tn.gif .
ln -s ../img_photos/taj_mahal_sm.png .
ln -s ../img_photos/shirt.jpg .

../generate_examples

../generate_compare
echo "DONE"

