#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ../generate_options
../generate_clear

ln -s ../images/colorspace_* .
ln -s ../images/compose_* .
ln -s ../img_photos/clip.jpg .
ln -s ../img_photos/wm.jpg .

../generate_examples

../generate_compare
echo "DONE"
