#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ../generate_options
../generate_clear

ln -s ../images/koala.gif .
ln -s ../images/rose.gif .
ln -s ../images/dragon_sm.gif .
ln -s ../img_photos/lena_orig.png .
ln -s ../img_photos/mandrill_grid_sm.jpg .
ln -s ../img_photos/flower_*.jpg .

../generate_examples

../generate_compare
echo "DONE"
