#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

if [ "X$1" != "X-f" ]; then
  echo >&2 "ABORTING generation for bugs examples -- use '-f' for force"
  exit 10
else
  shift
fi
. ../../generate_options
../../generate_clear

rm -f *.ico *.tif

. ../../generate_examples

../../generate_compare

echo "DONE"

