#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ../generate_options
../generate_clear

rm -f *.miff *.miff.gz *.mng

ln -s ../anim_basics/canvas_{prev,bgnd}.gif .
ln -s ../anim_basics/coalesce_frames.gif .
ln -s ../anim_basics/bunny_bgnd.gif .
ln -s ../anim_basics/bunny_bgnd_frames.gif .
ln -s ../images/{medical,paddleball}.gif .

../generate_examples

../generate_compare
echo "DONE"
