#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ./generate_options
./generate_clear

if false; then
  ( cd images
    echo "Generating Logo"
    ../scripts/generate_logo
    echo "Generating Test"
    ../scripts/generate_test
  )
fi

( cd images
  echo "Generating (small)Images Index"
  thumblinks -i -h .header.html -f .footer.html > INDEX.html
)
( cd img_www
  echo "Generating WWW Images Index"
  thumblinks -i -h .header.html -f .footer.html > INDEX.html
)
( cd img_diagrams
  echo "Generating Diagrams Index"
  thumblinks -i -h .header.html -f .footer.html > INDEX.html
)
( cd img_photos;
  echo "Generating Photo Index"
  ../scripts/generate_index
)

./generate_version >/dev/null

composite  -compose Dst_Over -tile pattern:checkerboard \
           images/test.png   test_undertile.jpg

chmod 644 *.{jpg,gif,html}

./generate_compare

echo "DONE"

