#!/bin/bash
#
# Clear out or backup old example images before generating new ones
#

# Source settings common to all examples
[ -f ./generate_options     ] && . ./generate_options
[ -f ../generate_options    ] && . ../generate_options
[ -f ../../generate_options ] && . ../../generate_options

# function to clear or backup old images...
echo "Backup of Old images"

clear_backup() {    # backup existing image, unless it is already backed up
  for file in "$@"; do
    echo "$file" | grep -q '^_' && continue
    [ -h "$file" ] && rm -f "$file"    # remove symlinks
    [ -f "_$file" ] && rm -f "$file"   # if backup, just delete non-backup
    [ ! -f "$file" ] && rm -f "$file"  # if not a file, just delete
    [ ! -f "$file" ] && continue       # skip if not a file
    [ ! -e "$file" ] && continue       # skip if does not exist
    if [ "$FORCE" ]; then
      rm -f "$file"           # remove file if forced full re-generation
    else
      mv -f "$file" "_$file"  # backup file (if not forced)
    fi
  done
}
clear_backup *.{jpg,png,gif,miff}
clear_backup *.{jpg,png,gif,miff}.*
clear_backup *.{txt,tif,anim,ppm,ps,utf8,svg,mvg}

rm -f png_ie.*   # temporary -- remove old links
rm -f  core*
rm -rf .xvpics

