#!/bin/bash
#
# Global image example generation
#
# Anthony Thyssen  <A.Thyssen@grffith.edu.au>

. ./generate_options

# ----------
echo "===== Top Level ====="
./generate >/dev/null

# DO NOT add other "bugs" except the testing directory
for i in \
  basics files formats text fonts annotating \
  thumbnails photos montage layers \
  anim_basics anim_opt anim_mods video \
  compare advanced backgrounds \
\
  canvas color_basics color_mods masking
  quantize crop resize filter filter/nicolas \
  compose compose/tables draw \
  warping distorts distorts/affine \
  transform mapping \
  blur morphology convolve fourier \
  antialiasing misc api windows bugs/testing
do
  echo "===== $i ====="
  ( cd $i || continue; ./generate >/dev/null; )
done

# -------------------------
