#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

if [ "X$1" != "X-f" ]; then
  echo >&2 "ABORTING generation for bugs examples -- use '-f' for force"
  exit 10
else
  shift
fi
. ../../generate_options
#../../generate_clear
#jpg_opt='-quality 100%'

#ln -s ../../images/dpat_*.gif .
#ln -s ../../images/dmap_*.png .

#export PATH="$HOME/store/IM/utilities:$PATH"
. ../../generate_examples

echo "DONE"

rm -f core*
