#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ../generate_options
../generate_clear

ln -s ../images/dragon_md.gif dragon.gif
ln -s ../images/tile_rings.jpg rings.jpg
ln -s ../images/{castle,frame,eyes}.gif .
ln -s ../images/{hand_point,paint_brush,scroll}.gif .
ln -s ../images/wmark_image.* .

../generate_examples

../generate_compare
echo "DONE"

