#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ../generate_options
../generate_clear

../generate_font_chars --append

ln -s ../images/font_[0-9].gif .
ln -s ../images/{balloon,medical,present,shading}.gif .
ln -s ../images/{castle,eye,eyeguy,ghost,hand_point}.gif .
ln -s ../images/{news,noseguy,paint_brush,pencil,recycle}.gif .
ln -s ../images/{skull,snowman,storm,terminal,tree}.gif .
ln -s ../images/tile_fabric.gif .f
ln -s ../images/push_pin.png .
ln -s ../images/map_venice* .
ln -s ../img_photos/holocaust_tn.gif .
ln -s ../img_photos/spiral_stairs_tn.gif .
ln -s ../img_photos/chinese_chess_tn.gif .

../generate_examples

../generate_compare
echo "DONE"

