#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ../generate_options
../generate_clear
rm -f dmap_hlines.pgm

ln -s ../images/rose.gif .
ln -s ../images/netscape.gif .
ln -s ../images/tree.gif .
ln -s ../images/colortable.gif .
ln -s ../images/colormap.gif .
ln -s ../images/colorwheel.png .
ln -s ../images/dpat_*.gif .
ln -s ../images/eyes.gif .
ln -s ../img_photos/parrots_med.png .
ln -s ../img_diagrams/cmyk_offset.png .

../generate_examples

../generate_compare
echo "DONE"

