#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ../generate_options
../generate_clear

ln -s ../images/star.gif .
ln -s ../images/font_[1-5].gif .

../generate_examples

./generate_border_compose
./generate_frame_compose

../generate_compare
echo "DONE"
