#!/bin/sh
#
# Generate a montage array of various cases of the wartermark
#
echo "Generating Border Compose Montage..."

. ../generate_options

color=limegreen
image=star.gif

list=
for compose in  Over Copy Src Dst Dst_In Dst_Out; do
  convert -label $compose  $image -bordercolor $color \
          -compose $compose -border 5  b_$compose.png
  list="$list b_$compose.png"
done

montage -tile x1 -geometry +15+2  -pointsize 10 \
        -background $page_bg_color -mattecolor $page_bg_color \
        $list  $jpg_opt border_compose.jpg

rm -rf b_*.png
chmod 644 border_compose.jpg

