#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ../generate_options
../generate_clear

ln -s ../images/{balloon,medical,present,shading}.gif .
ln -s ../images/script_k.gif .
ln -s ../images/smoke_skull*.gif .
ln -s ../images/dl_world*.gif .
ln -s ../images/bunny*.gif .

../generate_examples

../generate_compare
echo "DONE"

