#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ../generate_options
../generate_clear

ln -s ../images/koala.gif .
ln -sf ../images/swirl_video.* .
cp ../STORE/distorts/swirl_video.txt .

../generate_examples

if [ "$FORCE" ]; then
  echo "Animation Scripts..."
  echo "  animate_mixer...";        ./animate_mixer
  echo "  animate_whirlpool...";    ./animate_whirlpool
  echo "  animate_explode...";      ./animate_explode
  echo "  animate_flex...";         ./animate_flex
  echo "  animate_flag...";         ./animate_flag
  echo "  animate_rotate...";       ./animate_rotate
  #echo "  animate_affine_rot...";   ./animate_affine_rot
  echo "  animate_distort_rot...";  ./animate_distort_rot
else
  echo "Animation Scripts... (Recovering)"
  mved -q _animate_=.gif  animate_=.gif
fi

../generate_compare
echo "DONE"
