#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ../generate_options
../generate_clear

rm -f *.svg  marker*.dat

ln -s ../images/color_test.png .
ln -s ../images/terminal.gif .
ln -s ../images/diagonal.svg .
ln -s ../images/marker.png .
ln -s ../images/home.svg .
ln -s diagonal.svg diagonal.svg.txt

../generate_examples

../generate_compare
echo "DONE"
