#!/bin/sh
#
# Overlay multiple plasma images to produce a plasma image that can
# tile without showing up edges.
#
size=$1                            # size of the tile to produce


plasma="( plasma:fractal -blur 0x2 )"  # type of plasma image to use
half=`expr $size / 2`              # half the tile size
area="${size}x${size}"             # size as an area

convert -size $area xc: \
        -fx '(cos(264*(i/w-.5))*.6+.4)*(cos(264*(j/h-.5))*.6+.4)*1.1' \
        -write mpr:mask  +delete \
                            -size $area $plasma \
        -roll +$half+0      -size $area $plasma  mpr:mask +matte -composite \
        -roll -$half+$half  -size $area $plasma  mpr:mask +matte -composite \
        -roll +$half+0      -size $area $plasma  mpr:mask +matte -composite \
        -roll -$half-$half  "$2"

exit 0

