#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ../generate_options
../generate_clear

ln -s ../images/rose.gif .
ln -s ../images/flag.gif .
ln -s ../images/figure.gif .
ln -s ../images/disks.gif .
ln -s ../images/test_morphology.gif .
ln -s ../img_photos/rose_orig.png .

../generate_examples

../generate_compare
echo "DONE"
