#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ../generate_options
../generate_clear

ln -s ../images/rose.gif .
ln -s ../images/flag.gif .
ln -s ../images/shape_figure.gif figure.gif
ln -s ../images/shape_man.gif man.gif
ln -s ../images/shape_lines.gif lines.gif
ln -s ../images/shape_circles.gif circles.gif
ln -s ../images/shape_disks.gif disks.gif
ln -s ../images/test_morphology.gif test.gif
ln -s ../img_photos/rose_orig.png .

../generate_examples

../generate_compare
echo "DONE"
