#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ../generate_options
../generate_clear

rm -f *.avi

ln -s ../images/plane.avi .
ln -s ../images/colormap_332.png .
ln -s ../img_photos/video_frame.png .

../generate_examples

../generate_compare
echo "DONE"

