#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ../generate_options
../generate_clear

ln -s ../images/dragon_sm.gif .
ln -s ../images/terminal.gif .
ln -s ../images/rose.gif .
ln -s ../images/rose.png .
ln -s ../img_photos/earth_lights_4800.tif .

. ../generate_examples

../generate_compare
echo "DONE"

