#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ../generate_options
../generate_clear

ln -s ../images/rose.gif .
ln -s ../images/cow.gif .
ln -s ../images/colorwheel.png .
ln -s ../images/{balloon,present}.gif .
ln -s ../images/disks.gif  .

../generate_examples

../scripts/hsl_named_colors named_colors.png

../generate_compare
echo "DONE"
