#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ../generate_options
../generate_clear
#jpg_opt='-quality 100%'


ln -s ../images/dragon_sm.gif  .
ln -s ../images/cyclops_sm.gif  cyclops.gif
ln -s ../images/{bg,star,sphinx,hand_point}.gif .
ln -s ../images/tile_{aqua,water}.jpg .
ln -s ../images/text_scan.png .
ln -s ../images/overlay_*.gif .
ln -s ../images/koala.gif .
ln -s ../images/rose.png .
ln -s ../img_photos/flower_sm.jpg .

../generate_examples

echo ""

#Now generate the other montages
./generate_wmark    # must be first for wmark image
./generate_dissolve
./generate_blend

../generate_compare
echo "DONE"
