#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ../generate_options
../generate_clear

ln -s ../img_photos/building_[12].* .
ln -s ../img_photos/hugin.* .
ln -s ../img_photos/campmobile* .
ln -s ../img_photos/keyboards* .

../generate_examples

../generate_compare
echo "DONE"
