#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ../generate_options
../generate_clear
#jpg_opt='-quality 100%'

ln -s ../images/test.png .
ln -s ../images/rose.png .
ln -s ../images/tile_disks.jpg .
ln -s ../images/cow.gif .
ln -s ../img_photos/wedding_party_sm.jpg .
ln -s ../img_photos/zelda_dark_sm.png zelda.png
ln -s ../img_photos/port_sm.png port.png
ln -s ../img_photos/chinese_chess.jpg .

../generate_examples

# Junk the gunplot 'fit' output
rm -f fit.log

../generate_compare
echo "DONE"
