#!/bin/sh
#
# Generate a motage array of the letter A of the result of -gaussian
#
#  -gaussian <radius>{x<sigma>}
#
#
echo "Generating Blur Montage..."

. ../generate_options
#jpg_opt='-quality 100%'

#convert -size 100x100 xc:white -draw 'circle 50,50 35,50' gaussian.png
#convert -font Candice -pointsize 36 label:A \
#        -bordercolor white -border 20  gaussian_source.png

list=
for r in 1 2 5 0; do
  for s in 1 2 3 4 6 8; do
    convert -font Candice -pointsize 48 -label "-blur ${r}x${s}" \
            blur_source.png  -blur ${r}x${s}  blur_${r}x${s}.png
     list="$list blur_${r}x${s}.png"
  done
done

montage -tile 6x  -geometry +4+2  -pointsize 10 \
        -background $page_bg_color -mattecolor $page_bg_color \
        $list  $jpg_opt blur_montage.jpg

rm -f blur_[0-9]*.png
chmod 644 blur_montage.jpg


