#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ../generate_options
../generate_clear

ln -s ../images/rose.png .
ln -s ../images/rose_[fb]g_mask.png .
ln -s ../images/koala.gif .
ln -s ../images/knight.png .
ln -s ../images/cyclops.png .
ln -s ../images/moon.png .
ln -s ../images/tile_{disks,water,aqua}.jpg .
ln -s ../images/overlay_*.gif .
ln -s ../images/match_*.gif .
ln -s ../img_photos/zelda_tn.gif .

../generate_examples

../generate_compare
echo "DONE"
