#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ../generate_options
../generate_clear

rm *.pro
rm *.pgm

ln -s ../images/test.png .
ln -s ../images/bg.gif .
ln -s ../images/hand_point.gif .
ln -s ../images/iptcData.pro .

../generate_examples

../generate_compare
echo "DONE"

