#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ../generate_options
../generate_clear

ln -s ../images/face.png .
ln -s ../images/glider_gun.gif .
ln -s ../images/test_morphology.gif test.gif

convert ../images/shape_man.gif -crop 10x10+56+20! area.gif

../generate_examples

../generate_compare
echo "DONE"
