#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ../generate_options
. ../generate_clear
clear_backup *.svg

convert ../images/jigsaw_tmpl.png +matte -resize 64x64 mask.gif
ln -s ../images/piglet.gif .
ln -s ../images/rose* .
ln -s ../img_photos/spiral_stairs_sm.jpg .
ln -s ../images/shape_rectangle.gif .

../generate_examples

../generate_compare
echo "DONE"

