#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ../generate_options
../generate_clear
#jpg_opt='-quality 100%'

ln -s ../img_photos/clown_orig.jpg .
ln -s ../img_photos/clown_spectrum_mask.png .
ln -s ../img_photos/twigs_orig.jpg twigs.jpg
ln -s ../img_photos/twigs_spectrum_mask.png .
ln -s ../img_photos/lena_md.png lena.png
ln -s ../img_photos/holocaust_tn.gif .
ln -s ../img_photos/cameraman_sm.png .

../generate_examples

../generate_compare
echo "DONE"
