#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ../../generate_options
../../generate_clear

ln -s ../../images/koala.gif .
ln -s ../../img_photos/building.jpg .

../../generate_examples

../../generate_compare
echo "DONE"
