#!/bin/bash
#
# Regenerage all the images from the code blocks in the index.html
#

. ../generate_options
../generate_clear

ln -s ../images/bag_frame?.gif .

# Generate a impure Black and White image...
convert ../images/wmark_image.png -background white -flatten \
        -sigmoidal-contrast 10x50% wmark_dragon.jpg
chmod 644 wmark_dragon.jpg

../generate_examples

../generate_compare
echo "DONE"
